#!/bin/bash

#if system_matches "linux gentoo"; then
#  
#fi

cat >>$build_folder/init_db.sql <<EOF
create table if not exists host (
  host_id int auto_increment not null primary key
  , name varchar(25) not null
  , primary_ip varchar(50) not null
);

create table if not exists script (
  script_id int auto_increment not null primary key
  , name varchar(50) not null
  , version int not null
  , parameters varchar(255) not null
  , content text not null
);

create table if not exists task_request (
  task_request_id int auto_increment not null primary key
  , host_id int not null
  , wait_until datetime comment 'null means execute immediately'
  , script_id int not null
  , parameters varchar(255) not null
  , foreign key (host_id) references host(host_id) on update cascade on delete cascade
  , foreign key (script_id) references script(script_id) on update cascade on delete cascade
);

create table if not exists task_status_change (
  task_status_change_id int auto_increment not null primary key
  , task_request_id int not null
  , host_id int not null
  , wait_until datetime comment 'null means execute immediately'
  , script_id int not null
  , parameters varchar(255) not null
  , foreign key (host_id) references host(host_id) on update cascade on delete cascade
  , foreign key (script_id) references script(script_id) on update cascade on delete cascade
);

-- create agent user

EOF
