#!/bin/bash

# usage: cat file | hydrate_template >output
#   will replace bash variables and expressions
hydrate_template() {
try
  while IFS= read -r line; do
    line="${line//\"/\\\"}"
    eval "echo \"$line\"" || fail
  done
end_try
handle_return
}

