#!/bin/bash

# usage: cat file | hydrate_template >output
#   will replace bash variables and expressions
unset hydrate_template
hydrate_template() {
local returnValue=0
local OIFS="$IFS"
while true; do
    IFS=$'\n'
    while read -r line; do
        line="${line//\"/\\\"}"
        eval "echo \"$line\"" || fail
    done
    break
done
IFS="$OIFS"
return $returnValue
}

