#!/bin/bash

unalias fail &>/dev/null
alias fail='{ returnValue=1; break; }'
# should be placed after any loop inside of an exception catching block
unalias maybeBreak &>/dev/null
alias maybeBreak='[ $returnValue == 0 ] || break;'
unalias handleReturn &>/dev/null
alias handleReturn='return $returnValue'

