#!/bin/bash

# usage: cat file | hydrate_template >output
#   will replace bash variables and expressions
hydrate_template() {
local OIFS="$IFS"
try
  IFS=$'\n'
    while read -r line; do
      line="${line//\"/\\\"}"
      eval "echo \"$line\"" || fail
    done
end_try
IFS="$OIFS"
handle_return
}

